import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import useSWR from 'swr'

interface PrefList {
  prefCode: number
  prefName: string
}

interface Res {
  result: PrefList[]
}

const Home: NextPage = () => {
  const fetcher = (url: string) =>
    axios
      .get<Res>(url, {
        headers: { 'X-API-KEY': 'B54onZ294qfIEvmevUdQX9lOiKJrDnoNR7LYDrQ6' },
      })
      .then((res) => res.data)

  const { data, error } = useSWR(
    'https://opendata.resas-portal.go.jp/api/v1/prefectures',
    fetcher
  )

  console.log(data)

  return (
    <>
      <Head>
        <title>都道府県別人口推移</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data?.result.map((item) => {
          return <p key={item.prefCode}>{item.prefName}</p>
        })}
      </main>
    </>
  )
}

export default Home
